### ISSUE TITLE
Request for new sandbox project: pluggable components SDK

### ISSUE THREAD

**Issue by tmacam** [dapr/community#209] opened 2022-08-30 19:32 UTC
1. Describe how the Dapr community will benefit from this project? Please, describe one or more scenarios.
 
    [Pluggable Components] is a new feature targeted in development that allows for de definition of gRPC-based components that reside outside Dapr main binary. Having SDKs to ease the development of such components it would make contributors life easier and add velocity to the development of such components.

2. Which programming languages will be used?

    We are targeting SDKs in Java, Go and .Net.

3. Does the project have any hard dependency on other technologies or cloud vendors? Example: Kubernetes, Azure, AWS, Terraform

    No

4. Enumerate the repositories this project will need to be created.

    Repositories would follow the format `components-{lang}-sdk`. As of now, we are aiming at 3 SDKs and thus 3 repositories with the following suggested maintainers:
    
    | Repository name | Programming Language | Maintainers |
    |-|-|-|
    |`components-go-sdk`| Go | @mcandeia @tmacam|
    |`components-dotnet-sdk`| .Net | @johnewart @mcandeia |
    |`components-java-sdk`| Java | @tmacam @johnewart|

6. What is the ETA to have this project reach a stable version and graduate to the main Dapr organization?

   [Pluggable Components] is targeted to be released as an alpha feature on Dapr 1.9 release. I don't know if it will be release as a stable feature on 1.10. I don't think languages SDKs should reache stable before that.

7. Who are the maintainers of this project and corresponding employers?

    @tmacam, @mcandeia and @johnewart from Microsoft.

### Edit history

* **2022-09-06**: Updated suggested repository names to `components-{lang}-sdk` and associated repositories to suggested maintainers

[Pluggable Components]: https://github.com/dapr/dapr/issues/4925

**Comment by artursouza** [comment] 2022-09-02 20:38
I agree.

**Comment by tmacam** [comment] 2022-09-02 21:25
Not sure if it it would be better to have `{lang}-components-sdk` rather than `{lang}-component-sdk`.

**Comment by berndverst** [comment] 2022-09-02 23:54
Sounds good, but I prefer naming these "components-sdk-{lang}"

Easier to sort repos semantically this way!

**Comment by artursouza** [comment] 2022-09-02 23:57
> Sounds good, but I prefer naming these "components-sdk-{lang}"
> 
> 
> 
> Easier to sort repos semantically this way!

Yes. The problem is that it would be different from how we name SDKs today. Otherwise, I would be supportive. I think consistency here wins over the sorting thing.

**Comment by berndverst** [comment] 2022-09-03 00:00
> > Sounds good, but I prefer naming these "components-sdk-{lang}"
> > 
> > 
> > 
> > Easier to sort repos semantically this way!
> 
> Yes. The problem is that it would be different from how we name SDKs today. Otherwise, I would be supportive. I think consistency here wins over the sorting thing. 

I guess we will have to disagree. The sandbox org will grow full of repos and sorting there will be important IMO.

Today the SDKs are called "python-sdk" for example.

So how about "components-python-sdk" then? That's consistent and semantically sortable!

**Comment by artursouza** [comment] 2022-09-06 03:03
OK. I like `components-{lang}-sdk`.

**Comment by tmacam** [comment] 2022-09-06 16:49
Should I update the original request to `components-{lang}-sdk` ?

**Comment by artursouza** [comment] 2022-09-06 21:08
I approve this request, contingent the naming convention being `components-{lang}-sdk`.

**Comment by paulyuk** [comment] 2022-09-06 21:16
LGTM.

For #5 on ETA, how about at least state this in terms of either month-year, or months past `stable` of pluggable components feature itself in Dapr?  I think we're trying to understand if there is a plan and is it a very long time, or soon?

**Comment by yaron2** [comment] 2022-09-06 22:06
LGTM

**Comment by tmacam** [comment] 2022-09-06 22:08
I am tempted to answer that, with the exception APIs for [middleware components](https://github.com/dapr/dapr/issues/5135), this should stabilize in `next_stable+2`. This will depend on usage and how the community reacts to what we propose and how stable these interfaces are proved to be.

**Comment by msfussell** [comment] 2022-09-07 17:33
LGTM. Approve

**Comment by artursouza** [comment] 2022-09-07 19:02
Done. Closing this issue.

<img width="924" alt="image" src="https://user-images.githubusercontent.com/130954/188957044-f0af478d-8315-4f18-b6be-3c445cd6a8e3.png">

**Closed by artursouza** 2022-09-07 19:02 UTC
